name: flightstream
version: "1.0.0"
config-version: 2

profile: flightstream

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

models:
  flightstream:
    staging:
      +materialized: view
    marts:
      +materialized: table
